# Generated by Django 5.1.3 on 2026-01-04 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_type', models.CharField(choices=[('weapon', 'Оружие'), ('armor', 'Броня'), ('consumable', 'Расходуемое'), ('resource', 'Ресурс'), ('misc', 'Разное')], default='misc', max_length=20, verbose_name='Тип предмета')),
                ('equipment_slot', models.CharField(choices=[('weapon', 'Оружие'), ('torso', 'Торс'), ('head', 'Голова'), ('hands', 'Руки'), ('legs', 'Ноги'), ('feet', 'Ступни'), ('accessory', 'Аксессуар'), ('none', 'Не экипируется')], default='none', max_length=20, verbose_name='Слот экипировки')),
                ('rarity', models.CharField(choices=[('gray', 'Серый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, verbose_name='Редкость')),
                ('strength_bonus', models.IntegerField(default=0, verbose_name='Бонус к силе')),
                ('agility_bonus', models.IntegerField(default=0, verbose_name='Бонус к ловкости')),
                ('vitality_bonus', models.IntegerField(default=0, verbose_name='Бонус к живучести')),
                ('attack_bonus', models.IntegerField(default=0, verbose_name='Бонус к атаке')),
                ('defense_bonus', models.IntegerField(default=0, verbose_name='Бонус к защите')),
                ('health_bonus', models.IntegerField(default=0, verbose_name='Бонус к здоровью')),
                ('crit_chance_bonus', models.FloatField(default=0.0, verbose_name='Бонус к шансу крита (%)')),
                ('dodge_chance_bonus', models.FloatField(default=0.0, verbose_name='Бонус к шансу уворота (%)')),
                ('value', models.IntegerField(default=0, verbose_name='Цена предмета')),
                ('stackable', models.BooleanField(default=False, verbose_name='Можно складывать')),
                ('max_stack', models.IntegerField(default=1, verbose_name='Максимум в стопке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('twitch_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch username')),
                ('twitch_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch ID')),
                ('twitch_access_token', models.TextField(blank=True, null=True, verbose_name='Twitch access token')),
                ('twitch_refresh_token', models.TextField(blank=True, null=True, verbose_name='Twitch refresh token')),
                ('twitch_connected', models.BooleanField(default=False, verbose_name='Twitch подключен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя персонажа')),
                ('strength', models.IntegerField(default=5, verbose_name='Сила')),
                ('agility', models.IntegerField(default=5, verbose_name='Ловкость')),
                ('vitality', models.IntegerField(default=5, verbose_name='Живучесть')),
                ('free_skill_points', models.IntegerField(default=5, verbose_name='Свободные очки навыков')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('max_health', models.IntegerField(default=100, verbose_name='Максимальное здоровье')),
                ('current_health', models.IntegerField(default=100, verbose_name='Текущее здоровье')),
                ('min_attack', models.IntegerField(default=10, verbose_name='Минимальная атака')),
                ('max_attack', models.IntegerField(default=15, verbose_name='Максимальная атака')),
                ('defense', models.IntegerField(default=5, verbose_name='Защита')),
                ('crit_chance', models.FloatField(default=5.0, verbose_name='Шанс крита (%)')),
                ('dodge_chance', models.FloatField(default=5.0, verbose_name='Шанс уворота (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('gold', models.IntegerField(default=100, verbose_name='Золото')),
                ('total_games', models.IntegerField(default=0, verbose_name='Всего игр')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед')),
                ('losses', models.IntegerField(default=0, verbose_name='Поражений')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
                'ordering': ['-level', '-experience'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('weapon', 'Оружие'), ('torso', 'Торс')], max_length=20, unique=True, verbose_name='Слот')),
                ('equipped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата экипировки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='game.character', verbose_name='Персонаж')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Экипировка',
                'verbose_name_plural': 'Экипировки',
                'unique_together': {('character', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Предмет')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
                'ordering': ['-obtained_at'],
                'unique_together': {('player', 'item')},
            },
        ),
    ]
