# Generated by Django 5.1.3 on 2026-01-02 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя персонажа')),
                ('class_type', models.CharField(choices=[('warrior', 'Воин'), ('mage', 'Маг'), ('assassin', 'Ассасин')], max_length=20, verbose_name='Класс')),
                ('image', models.CharField(default='warrior.jpg', max_length=100, verbose_name='Изображение')),
                ('strength', models.IntegerField(default=10, verbose_name='Сила')),
                ('agility', models.IntegerField(default=10, verbose_name='Ловкость')),
                ('intelligence', models.IntegerField(default=10, verbose_name='Интеллект')),
                ('vitality', models.IntegerField(default=10, verbose_name='Живучесть')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game.playerprofile', verbose_name='Профиль игрока')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['-created_at'],
            },
        ),
    ]
