# Generated by Django 5.1.3 on 2026-01-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='player_profile',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='vitality',
        ),
        migrations.AddField(
            model_name='character',
            name='base_attack',
            field=models.IntegerField(default=10, verbose_name='Базовая атака'),
        ),
        migrations.AddField(
            model_name='character',
            name='base_defense',
            field=models.IntegerField(default=5, verbose_name='Базовая защита'),
        ),
        migrations.AddField(
            model_name='character',
            name='base_speed',
            field=models.IntegerField(default=10, verbose_name='Базовая скорость'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=100, verbose_name='Текущее здоровье'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_mana',
            field=models.IntegerField(default=50, verbose_name='Текущая мана'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100, verbose_name='Максимальное здоровье'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_mana',
            field=models.IntegerField(default=50, verbose_name='Максимальная мана'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='game.player', verbose_name='Игрок'),
        ),
    ]
