# Generated by Django 5.1.3 on 2026-01-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_character_options_remove_character_agility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitch_connected',
            field=models.BooleanField(default=False, verbose_name='Twitch подключен'),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch username'),
        ),
    ]
