# Generated by Django 5.1.3 on 2026-01-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_twitch_connected_player_twitch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitch_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Twitch access token'),
        ),
        migrations.AddField(
            model_name='player',
            name='twitch_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Twitch refresh token'),
        ),
    ]
