# Generated by Django 5.1.3 on 2026-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_twitch_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='base_attack',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_defense',
        ),
        migrations.RemoveField(
            model_name='character',
            name='base_speed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='class_type',
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=5, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='character',
            name='crit_chance',
            field=models.FloatField(default=5.0, verbose_name='Шанс крита (%)'),
        ),
        migrations.AddField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=5, verbose_name='Защита'),
        ),
        migrations.AddField(
            model_name='character',
            name='dodge_chance',
            field=models.FloatField(default=5.0, verbose_name='Шанс уворота (%)'),
        ),
        migrations.AddField(
            model_name='character',
            name='free_skill_points',
            field=models.IntegerField(default=5, verbose_name='Свободные очки навыков'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_attack',
            field=models.IntegerField(default=15, verbose_name='Максимальная атака'),
        ),
        migrations.AddField(
            model_name='character',
            name='min_attack',
            field=models.IntegerField(default=10, verbose_name='Минимальная атака'),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=10, verbose_name='Скорость'),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=5, verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='character',
            name='vitality',
            field=models.IntegerField(default=5, verbose_name='Живучесть'),
        ),
    ]
