# Generated by Django 5.1.3 on 2026-01-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_character_base_attack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_mana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_mana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
    ]
