# Generated by Django 5.1.3 on 2026-01-03 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_character_current_mana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_type', models.CharField(choices=[('weapon', 'Оружие'), ('armor', 'Броня'), ('consumable', 'Расходуемое'), ('resource', 'Ресурс'), ('misc', 'Разное')], default='misc', max_length=20, verbose_name='Тип предмета')),
                ('equipment_slot', models.CharField(choices=[('weapon', 'Оружие'), ('torso', 'Торс'), ('head', 'Голова'), ('hands', 'Руки'), ('legs', 'Ноги'), ('feet', 'Ступни'), ('accessory', 'Аксессуар'), ('none', 'Не экипируется')], default='none', max_length=20, verbose_name='Слот экипировки')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, verbose_name='Редкость')),
                ('attack_bonus', models.IntegerField(default=0, verbose_name='Бонус к атаке')),
                ('defense_bonus', models.IntegerField(default=0, verbose_name='Бонус к защите')),
                ('health_bonus', models.IntegerField(default=0, verbose_name='Бонус к здоровью')),
                ('crit_chance_bonus', models.FloatField(default=0.0, verbose_name='Бонус к шансу крита (%)')),
                ('dodge_chance_bonus', models.FloatField(default=0.0, verbose_name='Бонус к шансу уворота (%)')),
                ('value', models.IntegerField(default=0, verbose_name='Цена предмета')),
                ('stackable', models.BooleanField(default=False, verbose_name='Можно складывать')),
                ('max_stack', models.IntegerField(default=1, verbose_name='Максимум в стопке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('obtained_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.player', verbose_name='Игрок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
                'ordering': ['-obtained_at'],
                'unique_together': {('player', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('weapon', 'Оружие'), ('torso', 'Торс')], max_length=20, unique=True, verbose_name='Слот')),
                ('equipped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата экипировки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='game.character', verbose_name='Персонаж')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Экипировка',
                'verbose_name_plural': 'Экипировки',
                'unique_together': {('character', 'slot')},
            },
        ),
    ]
