# Generated by Django 5.1.3 on 2026-01-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_item_inventory_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='agility_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус к ловкости'),
        ),
        migrations.AddField(
            model_name='item',
            name='strength_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус к силе'),
        ),
        migrations.AddField(
            model_name='item',
            name='vitality_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус к живучести'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('gray', 'Серый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, verbose_name='Редкость'),
        ),
    ]
