# Generated by Django 5.1.3 on 2026-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_craftable',
            field=models.BooleanField(default=False, verbose_name='Крафтовый предмет'),
        ),
    ]
