# Generated by Django 5.1.3 on 2026-01-04 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('int', 'Целое число'), ('float', 'Дробное число'), ('bool', 'Логическое'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Тип значения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка игры',
                'verbose_name_plural': 'Настройки игры',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('debug', 'Отладка')], default='info', max_length=20, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character', verbose_name='Персонаж')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Лог игры',
                'verbose_name_plural': 'Логи игры',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='core_gamelo_level_3ae655_idx'), models.Index(fields=['source', 'created_at'], name='core_gamelo_source_142d00_idx')],
            },
        ),
    ]
