# Generated by Django 5.1.3 on 2026-01-04 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('twitch_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch username')),
                ('twitch_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitch ID')),
                ('twitch_access_token', models.TextField(blank=True, null=True, verbose_name='Twitch access token')),
                ('twitch_refresh_token', models.TextField(blank=True, null=True, verbose_name='Twitch refresh token')),
                ('twitch_connected', models.BooleanField(default=False, verbose_name='Twitch подключен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('gold', models.IntegerField(default=100, verbose_name='Золото')),
                ('total_games', models.IntegerField(default=0, verbose_name='Всего игр')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед')),
                ('losses', models.IntegerField(default=0, verbose_name='Поражений')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последний вход')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Профиль игрока',
                'verbose_name_plural': 'Профили игроков',
                'ordering': ['-level', '-experience'],
            },
        ),
    ]
