# Generated by Django 5.1.3 on 2026-01-04 13:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя персонажа')),
                ('strength', models.IntegerField(default=5, verbose_name='Сила')),
                ('agility', models.IntegerField(default=5, verbose_name='Ловкость')),
                ('vitality', models.IntegerField(default=5, verbose_name='Живучесть')),
                ('free_skill_points', models.IntegerField(default=5, verbose_name='Свободные очки навыков')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('max_health', models.IntegerField(default=100, verbose_name='Максимальное здоровье')),
                ('current_health', models.IntegerField(default=100, verbose_name='Текущее здоровье')),
                ('min_attack', models.IntegerField(default=10, verbose_name='Минимальная атака')),
                ('max_attack', models.IntegerField(default=15, verbose_name='Максимальная атака')),
                ('defense', models.IntegerField(default=5, verbose_name='Защита')),
                ('crit_chance', models.FloatField(default=5.0, verbose_name='Шанс крита (%)')),
                ('dodge_chance', models.FloatField(default=5.0, verbose_name='Шанс уворота (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='accounts.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('weapon', 'Оружие'), ('torso', 'Торс')], max_length=20, unique=True, verbose_name='Слот')),
                ('equipped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата экипировки')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='characters.character', verbose_name='Персонаж')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Экипировка',
                'verbose_name_plural': 'Экипировки',
                'unique_together': {('character', 'slot')},
            },
        ),
    ]
